version: '2.1'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
    - 1883:1883
    - 9001:9001
    networks:
      - default 
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
     - mqttexporter
    ports:
    - 9090:9090/tcp
    volumes:
    - ./prometheus/config.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - default
      
  mqttexporter:
    image: paderborn/mqttexporter
    container_name: mqttexporter
    depends_on:
       - mosquitto
    ports:
    - 9089:9089
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=senml/diatomic/#
    networks:
      - default
  prometheus_kafka_adapter:    
    image: telefonica/prometheus-kafka-adapter:1.2.0
    container_name: prometheus_kafka_adapter
    environment:
      KAFKA_BROKER_LIST: kafka:9092
      KAFKA_TOPIC: senml    
  #prometheus_postgresql_adapter:
  #  container_name: prometheus_pg_adapter
  #  depends_on:
  #   - prometheus
  #  environment:
  #    TS_PROM_LOG_LEVEL: debug
  #    TS_PROM_PG_DB_CONNECT_RETRIES: 10
  #    TS_PROM_PG_HOST: 191.168.99.100
  #    TS_PROM_PG_PASSWORD: postgres
  #    TS_PROM_PG_SCHEMA: postgres
  #    TS_PROM_WEB_TELEMETRY_PATH: /metrics-text
  #  image: timescale/prometheus-postgresql-adapter:latest
  #  ports:
  #  - 9201:9201/tcp
  #  command: "-pg.host=prometheus_postgres -pg.prometheus-log-samples -pg.password=postgres"
  #  networks:
  #    - default
networks:
  default:
    external:
      name: egm
    
