version: '2.1'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
    - 2181
    networks:
    - default
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    container_name: kafka
    depends_on:
    - zookeeper
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    networks:
    - default
  kafkaexporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafkaexporter
    depends_on:
    - kafka
    command: --kafka.server=kafka:9092  --topic.filter=senml
    ports:
    - 9308:9308
    networks:
    - default      
  prometheus_kafka_adapter:    
    image: telefonica/prometheus-kafka-adapter:1.2.0
    container_name: prometheus_kafka_adapter
    depends_on:
     - kafka
    environment:
      KAFKA_BROKER_LIST: 192.168.99.100:9092
      KAFKA_TOPIC: senml  
networks:
  default:
    external:
      name: egm
    
